### ISSUE TITLE
Issue building pytsk3 from pypi

### ISSUE THREAD

**Issue by joachimmetz** [py4n6/pytsk#15]
https://pypi.python.org/pypi/pytsk3
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define init function (initpytsk3)
```

**Comment by joachimmetz** [comment]
New sdist uploaded to pypi

**Comment by joachimmetz** [comment]
```
Collecting pytsk3
  Using cached pytsk3-20160217.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-QKwm0B/pytsk3/setup.py", line 71, in <module>
        'setuptools minimum required version: %s' % SETUPTOOLS_MIN_VER
    RuntimeError: setuptools minimum required version: 19
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-QKwm0B/pytsk3/setup.py", line 71, in <module>
    
        'setuptools minimum required version: %s' % SETUPTOOLS_MIN_VER
    
    RuntimeError: setuptools minimum required version: 19
    
```

**Comment by scudette** [comment]
Oh sorry, I forgot to upload a copy of the latest version. This copy was still the old fragile build which depended on the specific setuptools version. Please try 20160219.post1.

**Comment by joachimmetz** [comment]
Thx, new version works for me.
