### ISSUE TITLE
Sample fls.py -r option doesn't work for NTFS filesystem image

### ISSUE THREAD

**Issue by joachimmetz** [py4n6/pytsk#2]
samples/fls.py with -r option:

```
python pytsk/samples/fls.py -r -f ntfs -o 1048576 /mnt/hgfs/host_C_drive/case/test.dd
```

Then the following errors happened.

```
r/r 4-128-4:    $AttrDef
Traceback (most recent call last):
  File "pytsk/samples/fls.py.orig", line 155, in <module>
    list_directory(directory, [])
  File "pytsk/samples/fls.py.orig", line 143, in list_directory
    dir = f.as_directory()
IOError: File_as_directory: (tsk3.c:514) Not a directory
```

so I modified fls.py in list_directory function.

```
      #except RuntimeError: pass
      except IOError: pass
```

then executed again, but another error:

```
r/r 4-128-4:    $AttrDef
r/r 8-128-2:    $BadClus
r/r 8-128-1:    $BadClus:$Bad
Traceback (most recent call last):
  File "pytsk/samples/fls.py.orig", line 156, in <module>
    list_directory(directory, [])
  File "pytsk/samples/fls.py.orig", line 154, in list_directory
    stack.pop(-1)
IndexError: pop from empty list
```

**Comment by joachimmetz** [comment]
won't fix
