### ISSUE TITLE
Update README to add setup.py update

### ISSUE THREAD

**Issue by rgayon** [py4n6/pytsk#25]
running python setyp.py update is required to bootstrap the sleuthkit building process.

$ git clone https://github.com/py4n6/pytsk
$ python setup.py build
running build
running build_ext
sh: configure: No such file or directory
Traceback (most recent call last):
  File "setup.py", line 374, in <module>
    ProjectBuilder(setup_args, sys.argv).build()
  File "setup.py", line 369, in build
    **self._project_config
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 172, in run
    self.define = self.configure_source_tree(compiler)
  File "setup.py", line 153, in configure_source_tree
    output = subprocess.check_output(command, cwd="sleuthkit")
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['sh', 'configure', '--disable-java', '--without-afflib', '--without-libewf', '--without-zlib']' returned non-zero exit status 127

**Comment by joachimmetz** [comment]
This should only be needed for maintainers. See: https://github.com/py4n6/pytsk/wiki/Maintainers-guide
